apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-leaders-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-leaders-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-leaders-app
    spec:
      containers:
        - name: devops-leaders-app
          image: ghcr.io/deftdot/devops-leaders-course-v2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: devops-leaders-app-config
                  key: APP_NAME
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: devops-leaders-app-config
                  key: APP_VERSION
            - name: API_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: devops-leaders-app-config
                  key: API_TIMEOUT
            - name: STRESS_TEST_FLAG
              valueFrom:
                configMapKeyRef:
                  name: devops-leaders-app-config
                  key: STRESS_TEST_FLAG
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi