apiVersion: v1
kind: Service
metadata:
  name: devops-leaders-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: devops-leaders-app