name: CI Pipeline with Docker

on:
  workflow_dispatch:
  push:
    branches: [docker-ci]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t fastapi-dev .

    - name: Run tests inside Docker container
      run: |
        docker run --rm fastapi-dev /bin/bash -c "
          pip install pytest httpx black bandit pip-audit detect-secrets &&
          chmod +x run_tests.sh &&
          ./run_tests.sh
        "

    - name: Verify application starts inside Docker container
      run: |
        docker run --rm -d --name fastapi-test -p 8000:8000 fastapi-dev
        sleep 5
        CONTAINER_STATUS=$(docker inspect -f '{{.State.Running}}' fastapi-test)
        if [ \"$CONTAINER_STATUS\" = \"true\" ]; then
          echo \"Application started successfully\"
          docker stop fastapi-test
        else
          echo \"Application failed to start\"
          docker logs fastapi-test
          exit 1
        fi
